/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_chris_yanlong_PlayerView */

#ifndef _Included_com_chris_yanlong_PlayerView
#define _Included_com_chris_yanlong_PlayerView
#ifdef __cplusplus
extern "C" {
#endif
#undef com_chris_yanlong_PlayerView_NO_ID
#define com_chris_yanlong_PlayerView_NO_ID -1L
#undef com_chris_yanlong_PlayerView_VISIBLE
#define com_chris_yanlong_PlayerView_VISIBLE 0L
#undef com_chris_yanlong_PlayerView_INVISIBLE
#define com_chris_yanlong_PlayerView_INVISIBLE 4L
#undef com_chris_yanlong_PlayerView_GONE
#define com_chris_yanlong_PlayerView_GONE 8L
#undef com_chris_yanlong_PlayerView_DRAWING_CACHE_QUALITY_LOW
#define com_chris_yanlong_PlayerView_DRAWING_CACHE_QUALITY_LOW 524288L
#undef com_chris_yanlong_PlayerView_DRAWING_CACHE_QUALITY_HIGH
#define com_chris_yanlong_PlayerView_DRAWING_CACHE_QUALITY_HIGH 1048576L
#undef com_chris_yanlong_PlayerView_DRAWING_CACHE_QUALITY_AUTO
#define com_chris_yanlong_PlayerView_DRAWING_CACHE_QUALITY_AUTO 0L
#undef com_chris_yanlong_PlayerView_SCROLLBARS_INSIDE_OVERLAY
#define com_chris_yanlong_PlayerView_SCROLLBARS_INSIDE_OVERLAY 0L
#undef com_chris_yanlong_PlayerView_SCROLLBARS_INSIDE_INSET
#define com_chris_yanlong_PlayerView_SCROLLBARS_INSIDE_INSET 16777216L
#undef com_chris_yanlong_PlayerView_SCROLLBARS_OUTSIDE_OVERLAY
#define com_chris_yanlong_PlayerView_SCROLLBARS_OUTSIDE_OVERLAY 33554432L
#undef com_chris_yanlong_PlayerView_SCROLLBARS_OUTSIDE_INSET
#define com_chris_yanlong_PlayerView_SCROLLBARS_OUTSIDE_INSET 50331648L
#undef com_chris_yanlong_PlayerView_KEEP_SCREEN_ON
#define com_chris_yanlong_PlayerView_KEEP_SCREEN_ON 67108864L
#undef com_chris_yanlong_PlayerView_SOUND_EFFECTS_ENABLED
#define com_chris_yanlong_PlayerView_SOUND_EFFECTS_ENABLED 134217728L
#undef com_chris_yanlong_PlayerView_HAPTIC_FEEDBACK_ENABLED
#define com_chris_yanlong_PlayerView_HAPTIC_FEEDBACK_ENABLED 268435456L
#undef com_chris_yanlong_PlayerView_FOCUSABLES_ALL
#define com_chris_yanlong_PlayerView_FOCUSABLES_ALL 0L
#undef com_chris_yanlong_PlayerView_FOCUSABLES_TOUCH_MODE
#define com_chris_yanlong_PlayerView_FOCUSABLES_TOUCH_MODE 1L
#undef com_chris_yanlong_PlayerView_FOCUS_BACKWARD
#define com_chris_yanlong_PlayerView_FOCUS_BACKWARD 1L
#undef com_chris_yanlong_PlayerView_FOCUS_FORWARD
#define com_chris_yanlong_PlayerView_FOCUS_FORWARD 2L
#undef com_chris_yanlong_PlayerView_FOCUS_LEFT
#define com_chris_yanlong_PlayerView_FOCUS_LEFT 17L
#undef com_chris_yanlong_PlayerView_FOCUS_UP
#define com_chris_yanlong_PlayerView_FOCUS_UP 33L
#undef com_chris_yanlong_PlayerView_FOCUS_RIGHT
#define com_chris_yanlong_PlayerView_FOCUS_RIGHT 66L
#undef com_chris_yanlong_PlayerView_FOCUS_DOWN
#define com_chris_yanlong_PlayerView_FOCUS_DOWN 130L
#undef com_chris_yanlong_PlayerView_MAX_DIFF
#define com_chris_yanlong_PlayerView_MAX_DIFF 500L
/*
 * Class:     com_chris_yanlong_PlayerView
 * Method:    init_media
 * Signature: (Ljava/lang/String;Ljava/lang/Integer;Ljava/lang/Integer;Ljava/lang/Integer;)I
 */
JNIEXPORT jint JNICALL Java_com_chris_yanlong_PlayerView_init_1media
  (JNIEnv *, jobject, jstring, jobject, jobject, jobject);

/*
 * Class:     com_chris_yanlong_PlayerView
 * Method:    read_thread
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_chris_yanlong_PlayerView_read_1thread
  (JNIEnv *, jobject, jint );

/*
 * Class:     com_chris_yanlong_PlayerView
 * Method:    get_video_frame
 * Signature: (ILjava/lang/Double;Ljava/nio/ByteBuffer;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_chris_yanlong_PlayerView_get_1video_1frame
  (JNIEnv *, jobject, jint, jobject, jobject ,jint);

/*
 * Class:     com_chris_yanlong_PlayerView
 * Method:    get_audio_frame
 * Signature: (ILjava/lang/Double;Ljava/lang/Integer;Ljava/nio/ByteBuffer;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_chris_yanlong_PlayerView_get_1audio_1frame
  (JNIEnv *, jobject, jint, jobject, jobject, jobject);


JNIEXPORT jint JNICALL Java_com_chris_yanlong_PlayerView_seek_1frame
  (JNIEnv *, jobject, jint ,jint);


JNIEXPORT jint JNICALL Java_com_chris_yanlong_PlayerView_player_1stop
  (JNIEnv *, jobject, jint );

JNIEXPORT jint JNICALL Java_com_chris_yanlong_PlayerView_player_1release
  (JNIEnv *, jobject, jint );
#ifdef __cplusplus
}
#endif
#endif
